import { type ScanSection } from "./CollapsibleSection";

// Static metadata only. anchorId values confirmed against the jumpSections map in RunDetail.
type SectionMeta = Pick<ScanSection, "id" | "anchorId" | "title" | "summary" | "info">;

export const SECTION_ORDER = [
  "overview", "historic", "countyRecord", "permits", "ownership", "zoning", "valuation", "debt", "market", "transit", "newBusinessLicenses", "newConstruction",
  "crime", "proximity", "schools", "entCulture", "corridor", "development", "people", "incentives", "news",
] as const;

export const SECTION_META: Record<string, SectionMeta> = {
  overview: { id: "overview", anchorId: "print-section-property-info", title: "Property Overview",
    summary: "Address, PIN, zoning, building profile and lot — the basic facts.",
    info: ["Location map", "Facts: PIN, zoning, Opportunity-Zone flag", "Building profile: units, sqft, beds/baths, year", "Parcel / assessor record"] },
  historic: { id: "historic", anchorId: "print-section-historic-status", title: "Historic Status",
    summary: "Chicago Historic Resources Survey rating and designation signals.",
    info: ["CHRS survey rating", "Municipal designation signals", "Demolition-hold rule", "Credit eligibility requirements"] },
  countyRecord: { id: "countyRecord", anchorId: "print-section-county-record", title: "COUNTY RECORD",
    summary: "Cook County Assessor and Treasurer record for the subject parcel.",
    info: ["Parcel and structure facts", "Recorded unit configuration", "Assessor valuation inputs", "PIN and source links"] },
  permits: { id: "permits", anchorId: "section-permits", title: "Permits & Violations",
    summary: "Building permits, professionals on record, and code violations.",
    info: ["Permit history — current vs prior owner", "Professionals who worked on the building", "Building violations", "Sidewalk cafe permits", "MBE/WBE/DBE/VBE/BEPD are City of Chicago vendor certifications (minority-, women-, disadvantaged-, veteran-owned, and business enterprises owned by people with disabilities). We show them as reported by the city directory; we do not verify current standing."] },
  zoning: { id: "zoning", anchorId: "print-section-zoning-details", title: "Zoning & What You Can Build",
    summary: "What the zoning lets you build, by-right or with approvals.",
    info: ["Zoning district & meaning", "Allowed uses — as-of-right", "Your project-use verdict", "Development potential: FAR, height, parking", "Zoning & ZBA history"] },
  valuation: { id: "valuation", anchorId: "section-rentcast", title: "Valuation & Cashflow",
    summary: "Cap rate, cash flow and debt coverage at your inputs.",
    info: ["Deal inputs — price & financing", "Income → NOI statement", "Cap rate & cash flow", "DSCR coverage", "Market rents (RentCast)", "Short-term rental (Airbnb)"] },
  ownership: { id: "ownership", anchorId: "section-ownership", title: "Ownership & Title",
     summary: "Sale history, recorded debt, liens, and title status.",
     info: ["Chain of title", "Debt on title", "Title claims and filings", "Owner-name lien search", "Current owner & entity"] },
  debt: { id: "debt", anchorId: "print-section-pre-title-check", title: "Pre-Title Check",
     summary: "Property tax, financing readiness, and closing flags.",
     info: ["Property tax, exemptions & appeals", "Financing readiness", "Closing flags"] },
  market: { id: "market", anchorId: "print-section-mortgage-lending", title: "Mortgage & Lending Market",
    summary: "Who lends here, on what terms, and what has been changing hands.",
    info: ["Residential mortgage market (HMDA)", "Area transaction trends", "Recently sold comps", "Commercial lending — SBA 504", "Commercial lending — SBA 7(a)"] },
  transit: { id: "transit", anchorId: "print-section-transit", title: "Transit Access",
    summary: "Rail, Metra, bus and street traffic near the property.",
    info: ["CTA rail — nearest stations & ridership", "Metra — stations & ridership", "CTA bus — routes & ridership", "Street traffic volume (ADT)"] },
  newBusinessLicenses: { id: "newBusinessLicenses", anchorId: "print-section-new-business-licenses", title: "New Business Licenses",
    summary: "New business issuances and formation change within one mile.",
    info: ["Distinct businesses, not raw license records", "Current and prior 12-month formation", "New-issuance license mix", "Nearest openings"] },
  newConstruction: { id: "newConstruction", anchorId: "print-section-new-construction", title: "New Construction",
    summary: "Nearby new-construction permits, permit mix, and building activity within one mile.",
    info: ["One-mile parcel-specific permit scope", "Permit mix, unit counts and median reported cost", "18-month likely-still-building proxy", "Community area count is benchmark context only"] },
  crime: { id: "crime", anchorId: "section-crime", title: "Safety & Crime",
    summary: "Area crime levels, percentile vs the city, and trend.",
    info: ["Area crime statistics", "Tract percentile vs city", "Trend over time"] },
  proximity: { id: "proximity", anchorId: "print-section-proximity-details", title: "Proximity",
    summary: "Nearby parks, hospitals, landmarks of daily life, and vacant buildings.",
    info: ["Nearest park, hospital, university and stadium", "Nearest highway, bike trail and lake", "Vacant buildings, land and foreclosures"] },
  schools: { id: "schools", anchorId: "print-section-schools-daycare", title: "Schools & Childcare",
    summary: "Licensed childcare supply and CPS schools within the nearby search radius.",
    info: ["Childcare supply by ZIP or neighborhood", "Elementary, middle and high schools within 1.5 miles", "Attendance-boundary status of each school, not address assignment"] },
  entCulture: { id: "entCulture", anchorId: "print-section-entertainment-culture", title: "Entertainment & Culture",
    summary: "Michelin and James Beard dining, murals, landmarks and galleries within a mile.",
    info: ["Michelin Guide and James Beard restaurants", "Registered murals and architectural landmarks", "Licensed art galleries"] },
  corridor: { id: "corridor", anchorId: "print-section-neighborhood-news", title: "Corridor Intelligence",
    summary: "New businesses and news on the nearby commercial corridors.",
    info: ["New business licenses on the corridor", "Corridor news coverage", "Neighborhood news"] },
  development: { id: "development", anchorId: "print-section-upcoming-developments", title: "Nearby Development & Construction",
    summary: "New-construction permits and proposed projects nearby.",
    info: ["New-construction permits (radius-wide)", "Upcoming / proposed developments"] },
  people: { id: "people", anchorId: "print-section-demographics", title: "Neighborhood & People",
    summary: "Demographics, income, tenure and workforce (context only).",
    info: ["Demographic trends", "Languages spoken", "Vehicle ownership", "Senior population", "Jobs & workforce", "Voting & civic lean (context only)"] },
  incentives: { id: "incentives", anchorId: "print-section-location-incentives", title: "Incentives",
    summary: "Which incentive programs the parcel is eligible for.",
    info: ["Eligible / not-eligible program cards", "TIF, OZ, TOD, SBIF, NMTC", "Class 6b / 7, HUBZone, QCT", "Neighborhood Opportunity Fund, ADU…"] },
  news: { id: "news", anchorId: "section-address-news", title: "News on This Property",
    summary: "Any news coverage that names this specific property.",
    info: ["Articles naming the subject parcel", "Current-status check vs the record"] },
};
