import { type ScanSection } from "./CollapsibleSection";

// Static metadata only. anchorId values confirmed against the jumpSections map in RunDetail.
type SectionMeta = Pick<ScanSection, "id" | "anchorId" | "title" | "summary" | "info">;

export const SECTION_ORDER = [
  "overview", "historic", "permits", "ownership", "zoning", "valuation", "debt", "market", "transit", "newBusinessLicenses", "newConstruction",
  "crime", "proximity", "corridor", "development", "people", "incentives", "news",
] as const;

export const SECTION_META: Record<string, SectionMeta> = {
  overview: { id: "overview", anchorId: "print-section-property-info", title: "Property Overview",
    summary: "Address, PIN, zoning, building profile and lot — the basic facts.",
    info: ["Location map", "Facts: PIN, zoning, Opportunity-Zone flag", "Building profile: units, sqft, beds/baths, year", "Parcel / assessor record"] },
  historic: { id: "historic", anchorId: "print-section-historic-status", title: "Historic Status",
    summary: "Chicago Historic Resources Survey rating and designation signals.",
    info: ["CHRS survey rating", "Municipal designation signals", "Demolition-hold rule", "Credit eligibility requirements"] },
  permits: { id: "permits", anchorId: "section-permits", title: "Permits & Violations",
    summary: "Building permits, professionals on record, and code violations.",
    info: ["Permit history — current vs prior owner", "Professionals who worked on the building", "Building violations", "Sidewalk cafe permits", "MBE/WBE/DBE/VBE/BEPD are City of Chicago vendor certifications (minority-, women-, disadvantaged-, veteran-owned, and business enterprises owned by people with disabilities). We show them as reported by the city directory; we do not verify current standing."] },
  zoning: { id: "zoning", anchorId: "print-section-zoning-details", title: "Zoning & What You Can Build",
    summary: "What the zoning lets you build, by-right or with approvals.",
    info: ["Zoning district & meaning", "Allowed uses — as-of-right", "Your project-use verdict", "Development potential: FAR, height, parking", "Zoning & ZBA history"] },
  valuation: { id: "valuation", anchorId: "section-rentcast", title: "Valuation & Cashflow",
    summary: "Cap rate, cash flow and debt coverage at your inputs.",
    info: ["Deal inputs — price & financing", "Income → NOI statement", "Cap rate & cash flow", "DSCR coverage", "Market rents (RentCast)", "Short-term rental (Airbnb)"] },
  ownership: { id: "ownership", anchorId: "section-ownership", title: "Ownership & Title",
     summary: "Sale history, recorded debt, liens, and title status.",
     info: ["Chain of title", "Debt on title", "Title claims and filings", "Current owner & entity"] },
  debt: { id: "debt", anchorId: "print-section-pre-title-check", title: "Pre-Title Check",
     summary: "Property tax, financing readiness, and closing flags.",
     info: ["Property tax, exemptions & appeals", "Financing readiness", "Closing flags"] },
  market: { id: "market", anchorId: "print-section-comparable-sales", title: "The Local Market",
    summary: "Comps, price trends and mortgage-lending activity nearby.",
    info: ["Recently sold comps", "Area transaction trends", "HMDA — who’s borrowing", "HMDA — what’s getting funded", "Commercial lending (SBA)"] },
  transit: { id: "transit", anchorId: "print-section-transit", title: "Transit Access",
    summary: "Rail, Metra, bus and street traffic near the property.",
    info: ["CTA rail — nearest stations & ridership", "Metra — stations & ridership", "CTA bus — routes & ridership", "Street traffic volume (ADT)"] },
  newBusinessLicenses: { id: "newBusinessLicenses", anchorId: "print-section-new-business-licenses", title: "New Business Licenses",
    summary: "New business issuances and formation change within one mile.",
    info: ["Distinct businesses, not raw license records", "Current and prior 12-month formation", "New-issuance license mix", "Nearest openings"] },
  newConstruction: { id: "newConstruction", anchorId: "print-section-new-construction", title: "New Construction",
    summary: "Nearby new-construction permits, permit mix, and building activity within one mile.",
    info: ["One-mile parcel-specific permit scope", "Permit mix, unit counts and median reported cost", "18-month likely-still-building proxy", "Community area count is benchmark context only"] },
  crime: { id: "crime", anchorId: "section-crime", title: "Safety & Crime",
    summary: "Area crime levels, percentile vs the city, and trend.",
    info: ["Area crime statistics", "Tract percentile vs city", "Trend over time"] },
  proximity: { id: "proximity", anchorId: "print-section-proximity-details", title: "Proximity & Amenities",
    summary: "Parks, schools, hospitals, dining and other amenities.",
    info: ["Proximity grid: parks, hospital, stadium, lake", "Rated schools", "Grocery access", "Dining (Michelin + notable)", "Landmarks & culture", "Vacant / city-owned nearby"] },
  corridor: { id: "corridor", anchorId: "print-section-neighborhood-news", title: "Corridor Intelligence",
    summary: "New businesses and news on the nearby commercial corridors.",
    info: ["New business licenses on the corridor", "Corridor news coverage", "Neighborhood news"] },
  development: { id: "development", anchorId: "print-section-upcoming-developments", title: "Nearby Development & Construction",
    summary: "New-construction permits and proposed projects nearby.",
    info: ["New-construction permits (radius-wide)", "Upcoming / proposed developments"] },
  people: { id: "people", anchorId: "print-section-demographics", title: "Neighborhood & People",
    summary: "Demographics, income, tenure and workforce (context only).",
    info: ["Demographic trends", "Languages spoken", "Vehicle ownership", "Senior population", "Jobs & workforce", "Voting & civic lean (context only)"] },
  incentives: { id: "incentives", anchorId: "print-section-location-incentives", title: "Incentives",
    summary: "Which incentive programs the parcel is eligible for.",
    info: ["Eligible / not-eligible program cards", "TIF, OZ, TOD, SBIF, NMTC", "Class 6b / 7, HUBZone, QCT", "Neighborhood Opportunity Fund, ADU…"] },
  news: { id: "news", anchorId: "section-address-news", title: "News on This Property",
    summary: "Any news coverage that names this specific property.",
    info: ["Articles naming the subject parcel", "Current-status check vs the record"] },
};
