export type ZoningPermission = 'permitted' | 'special_use' | 'not_allowed';

export interface BusinessUse {
  name: string;
  category: string;
  zoningCategory: string;
  permissions: {
    residential: ZoningPermission;
    b1: ZoningPermission;
    b2: ZoningPermission;
    b3: ZoningPermission;
    c1: ZoningPermission;
    c2: ZoningPermission;
    c3: ZoningPermission;
    dc: ZoningPermission;
    dx: ZoningPermission;
    ds: ZoningPermission;
    m1: ZoningPermission;
    m2: ZoningPermission;
    m3: ZoningPermission;
    pmd: ZoningPermission;
  };
}

// Complete list based on Chicago Zoning Code Use Tables (17-2-0207, 17-3-0207, 17-4-0207, 17-5-0207)
export const BUSINESS_USES: BusinessUse[] = [
  // ============================================
  // A. RESIDENTIAL USES
  // ============================================
  {
    name: "Detached House",
    category: "Residential",
    zoningCategory: "Detached House",
    permissions: {
      residential: 'permitted',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'not_allowed',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'not_allowed',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Two-Flat",
    category: "Residential",
    zoningCategory: "Two-Flat",
    permissions: {
      residential: 'permitted',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'not_allowed',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'not_allowed',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Townhouse",
    category: "Residential",
    zoningCategory: "Townhouse",
    permissions: {
      residential: 'permitted',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Multi-Unit Residential",
    category: "Residential",
    zoningCategory: "Multi-Unit Residential",
    permissions: {
      residential: 'permitted',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Elderly Housing",
    category: "Residential",
    zoningCategory: "Elderly Housing",
    permissions: {
      residential: 'permitted',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Single-Room Occupancy (SRO)",
    category: "Residential",
    zoningCategory: "Single-Room Occupancy",
    permissions: {
      residential: 'special_use',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Artist Live/Work Space",
    category: "Residential",
    zoningCategory: "Artist Live/Work Space",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'permitted',
    }
  },
  {
    name: "Accessory Dwelling Unit (ADU)",
    category: "Residential",
    zoningCategory: "Accessory Dwelling Unit",
    permissions: {
      residential: 'permitted',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'not_allowed',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Additional Dwelling Unit",
    category: "Residential",
    zoningCategory: "Accessory Dwelling Unit",
    permissions: {
      residential: 'permitted',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'not_allowed',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },

  // ============================================
  // B. PUBLIC AND CIVIC USES
  // ============================================
  {
    name: "Assisted Living (Elderly Custodial Care)",
    category: "Public and Civic",
    zoningCategory: "Assisted Living/Elderly Custodial Care",
    permissions: {
      residential: 'permitted',
      b1: 'special_use',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Community Center / Recreation Building",
    category: "Public and Civic",
    zoningCategory: "Community Center/Recreation Building",
    permissions: {
      residential: 'special_use',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Convent / Monastery",
    category: "Public and Civic",
    zoningCategory: "Convent/Monastery",
    permissions: {
      residential: 'special_use',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Cultural Exhibit / Library / Museum",
    category: "Public and Civic",
    zoningCategory: "Cultural Exhibit/Library/Museum",
    permissions: {
      residential: 'special_use',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'special_use',
    }
  },
  {
    name: "Day Care Center",
    category: "Public and Civic",
    zoningCategory: "Day Care",
    permissions: {
      residential: 'permitted',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Domestic Violence Residence / Shelter",
    category: "Public and Civic",
    zoningCategory: "Domestic Violence Residence/Shelter",
    permissions: {
      residential: 'permitted',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Emergency Shelter",
    category: "Public and Civic",
    zoningCategory: "Emergency Shelter",
    permissions: {
      residential: 'special_use',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Hospital",
    category: "Public and Civic",
    zoningCategory: "Hospital",
    permissions: {
      residential: 'special_use',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'special_use',
      c1: 'special_use',
      c2: 'special_use',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Interim Housing",
    category: "Public and Civic",
    zoningCategory: "Interim Housing",
    permissions: {
      residential: 'special_use',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Nursing Home / Skilled Nursing Care",
    category: "Public and Civic",
    zoningCategory: "Nursing Home/Skilled Nursing Care",
    permissions: {
      residential: 'special_use',
      b1: 'special_use',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Police / Fire Station",
    category: "Public and Civic",
    zoningCategory: "Police/Fire Station",
    permissions: {
      residential: 'special_use',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Post Office",
    category: "Public and Civic",
    zoningCategory: "Post Office",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Religious Assembly (Church, Temple, Mosque)",
    category: "Public and Civic",
    zoningCategory: "Religious Assembly",
    permissions: {
      residential: 'special_use',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'special_use',
    }
  },
  {
    name: "Residential Care Home",
    category: "Public and Civic",
    zoningCategory: "Residential Care Home",
    permissions: {
      residential: 'permitted',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Residential Support Services",
    category: "Public and Civic",
    zoningCategory: "Residential Support Services",
    permissions: {
      residential: 'special_use',
      b1: 'special_use',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "School (Private K-12)",
    category: "Public and Civic",
    zoningCategory: "School",
    permissions: {
      residential: 'permitted',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'special_use',
      c1: 'special_use',
      c2: 'special_use',
      c3: 'special_use',
      dc: 'special_use',
      dx: 'special_use',
      ds: 'special_use',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "College / University",
    category: "Public and Civic",
    zoningCategory: "College/University",
    permissions: {
      residential: 'special_use',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'special_use',
      c1: 'special_use',
      c2: 'special_use',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Utility (Minor)",
    category: "Public and Civic",
    zoningCategory: "Utility, Minor",
    permissions: {
      residential: 'permitted',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Utility (Major)",
    category: "Public and Civic",
    zoningCategory: "Utility, Major",
    permissions: {
      residential: 'special_use',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'special_use',
      c1: 'special_use',
      c2: 'special_use',
      c3: 'special_use',
      dc: 'special_use',
      dx: 'special_use',
      ds: 'special_use',
      m1: 'special_use',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'special_use',
    }
  },
  {
    name: "Wireless Telecommunications Facility",
    category: "Public and Civic",
    zoningCategory: "Wireless Telecommunications Facility",
    permissions: {
      residential: 'special_use',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'special_use',
      c1: 'special_use',
      c2: 'special_use',
      c3: 'special_use',
      dc: 'special_use',
      dx: 'special_use',
      ds: 'special_use',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },

  // ============================================
  // C. COMMERCIAL USES
  // ============================================
  
  // C.1 Animal Services
  {
    name: "Animal Hospital / Veterinary",
    category: "Commercial - Animal Services",
    zoningCategory: "Animal Hospital/Vet",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Animal Grooming / Pet Store",
    category: "Commercial - Animal Services",
    zoningCategory: "Animal Grooming/Pet Store",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Kennel (Indoor Only)",
    category: "Commercial - Animal Services",
    zoningCategory: "Kennel",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'special_use',
      c1: 'not_allowed',
      c2: 'special_use',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Shelter (Animal)",
    category: "Commercial - Animal Services",
    zoningCategory: "Shelter, Animal",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'special_use',
      c1: 'not_allowed',
      c2: 'special_use',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'special_use',
    }
  },

  // C.2 Artist Work/Sales Space
  {
    name: "Artist Work or Sales Space",
    category: "Commercial - Arts",
    zoningCategory: "Artist Work or Sales Space",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'special_use',
    }
  },

  // C.3 Body Art Services
  {
    name: "Body Art Services (Tattoo, Piercing)",
    category: "Commercial - Personal Services",
    zoningCategory: "Body Art Services",
    permissions: {
      residential: 'not_allowed',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },

  // C.4 Building Maintenance Services
  {
    name: "Building Maintenance Services",
    category: "Commercial - Services",
    zoningCategory: "Building Maintenance Services",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'permitted',
      c1: 'not_allowed',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },

  // C.5 Business Support Services
  {
    name: "Business Support Services (Copy, Print, Mail)",
    category: "Commercial - Business Services",
    zoningCategory: "Business Support Services",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },

  // C.6 Communications Services
  {
    name: "Communications Services (Broadcasting Studio)",
    category: "Commercial - Media",
    zoningCategory: "Communications Services",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },

  // C.7 Consumer Laundry
  {
    name: "Laundromat / Dry Cleaner (Drop-off)",
    category: "Commercial - Services",
    zoningCategory: "Consumer Laundry/Cleaning",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },

  // C.8 Eating and Drinking Establishments
  {
    name: "Restaurant (No Liquor)",
    category: "Commercial - Food and Beverage",
    zoningCategory: "Eating and Drinking Establishments",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Restaurant (With Liquor)",
    category: "Commercial - Food and Beverage",
    zoningCategory: "Eating and Drinking Establishments",
    permissions: {
      residential: 'not_allowed',
      b1: 'special_use',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Coffee Shop / Cafe",
    category: "Commercial - Food and Beverage",
    zoningCategory: "Eating and Drinking Establishments",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Tavern / Bar",
    category: "Commercial - Food and Beverage",
    zoningCategory: "Tavern",
    permissions: {
      residential: 'not_allowed',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Brewpub / Winery (Tasting Room)",
    category: "Commercial - Food and Beverage",
    zoningCategory: "Tavern",
    permissions: {
      residential: 'not_allowed',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },

  // C.9 Entertainment and Spectator Sports
  {
    name: "Entertainment / Spectator Sports (Small)",
    category: "Commercial - Entertainment",
    zoningCategory: "Entertainment/Spectator Sports, Small",
    permissions: {
      residential: 'not_allowed',
      b1: 'special_use',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Entertainment / Spectator Sports (Medium)",
    category: "Commercial - Entertainment",
    zoningCategory: "Entertainment/Spectator Sports, Medium",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'special_use',
      b3: 'special_use',
      c1: 'not_allowed',
      c2: 'special_use',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Entertainment / Spectator Sports (Large)",
    category: "Commercial - Entertainment",
    zoningCategory: "Entertainment/Spectator Sports, Large",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'special_use',
      c1: 'not_allowed',
      c2: 'special_use',
      c3: 'special_use',
      dc: 'special_use',
      dx: 'special_use',
      ds: 'special_use',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Movie Theater",
    category: "Commercial - Entertainment",
    zoningCategory: "Entertainment/Spectator Sports, Small",
    permissions: {
      residential: 'not_allowed',
      b1: 'special_use',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Performing Arts Venue / Live Theater",
    category: "Commercial - Entertainment",
    zoningCategory: "Entertainment/Spectator Sports, Small",
    permissions: {
      residential: 'not_allowed',
      b1: 'special_use',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },

  // C.10 Financial Services
  {
    name: "Bank / Credit Union",
    category: "Commercial - Financial Services",
    zoningCategory: "Financial Services",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Currency Exchange",
    category: "Commercial - Financial Services",
    zoningCategory: "Currency Exchange",
    permissions: {
      residential: 'not_allowed',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Payday / Consumer Loan",
    category: "Commercial - Financial Services",
    zoningCategory: "Payday Loan/Consumer Loan",
    permissions: {
      residential: 'not_allowed',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'special_use',
      c1: 'special_use',
      c2: 'special_use',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Pawn Shop",
    category: "Commercial - Financial Services",
    zoningCategory: "Pawn Shop",
    permissions: {
      residential: 'not_allowed',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },

  // C.11 Food/Beverage Retail Sales
  {
    name: "Grocery Store / Supermarket",
    category: "Commercial - Retail",
    zoningCategory: "Food/Beverage Retail Sales",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Convenience Store",
    category: "Commercial - Retail",
    zoningCategory: "Food/Beverage Retail Sales",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Bakery (Retail)",
    category: "Commercial - Retail",
    zoningCategory: "Food/Beverage Retail Sales",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },

  // C.12 Funeral and Interment Services
  {
    name: "Funeral Home",
    category: "Commercial - Services",
    zoningCategory: "Funeral and Interment Services",
    permissions: {
      residential: 'special_use',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Cemetery / Mausoleum",
    category: "Commercial - Services",
    zoningCategory: "Cemetery/Cremating/Interment",
    permissions: {
      residential: 'special_use',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'not_allowed',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'special_use',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'permitted',
      pmd: 'special_use',
    }
  },

  // C.13 Liquor Sales
  {
    name: "Liquor Store (Package Goods)",
    category: "Commercial - Retail",
    zoningCategory: "Liquor Sales",
    permissions: {
      residential: 'not_allowed',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'special_use',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },

  // C.14 Lodging
  {
    name: "Hotel / Motel",
    category: "Commercial - Lodging",
    zoningCategory: "Lodging",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'special_use',
      c1: 'special_use',
      c2: 'special_use',
      c3: 'special_use',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Bed and Breakfast",
    category: "Commercial - Lodging",
    zoningCategory: "Bed and Breakfast",
    permissions: {
      residential: 'special_use',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'not_allowed',
      m2: 'not_allowed',
      m3: 'not_allowed',
      pmd: 'not_allowed',
    }
  },

  // C.15 Medical Service
  {
    name: "Medical / Dental Office",
    category: "Commercial - Medical",
    zoningCategory: "Medical Service",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Urgent Care / Walk-In Clinic",
    category: "Commercial - Medical",
    zoningCategory: "Medical Service",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Methadone Treatment Facility",
    category: "Commercial - Medical",
    zoningCategory: "Methadone Treatment Facility",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'special_use',
      b3: 'special_use',
      c1: 'not_allowed',
      c2: 'special_use',
      c3: 'special_use',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },

  // C.16 Office
  {
    name: "Office (Professional / Business)",
    category: "Commercial - Office",
    zoningCategory: "Office",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Coworking Space",
    category: "Commercial - Office",
    zoningCategory: "Office",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },

  // C.17 Parking (Non-Accessory)
  {
    name: "Parking Lot (Non-Accessory)",
    category: "Commercial - Parking",
    zoningCategory: "Parking, Non-Accessory",
    permissions: {
      residential: 'special_use',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'special_use',
      c1: 'special_use',
      c2: 'special_use',
      c3: 'permitted',
      dc: 'special_use',
      dx: 'special_use',
      ds: 'special_use',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Parking Garage (Non-Accessory)",
    category: "Commercial - Parking",
    zoningCategory: "Parking, Non-Accessory",
    permissions: {
      residential: 'special_use',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'special_use',
      c1: 'special_use',
      c2: 'special_use',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },

  // C.18 Personal Service
  {
    name: "Hair Salon / Barbershop",
    category: "Commercial - Personal Services",
    zoningCategory: "Personal Service",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Nail Salon",
    category: "Commercial - Personal Services",
    zoningCategory: "Personal Service",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Spa / Massage",
    category: "Commercial - Personal Services",
    zoningCategory: "Personal Service",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },

  // C.19 Recreation
  {
    name: "Health Club / Gym",
    category: "Commercial - Recreation",
    zoningCategory: "Indoor Recreation",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Bowling Alley",
    category: "Commercial - Recreation",
    zoningCategory: "Indoor Recreation",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Skating Rink",
    category: "Commercial - Recreation",
    zoningCategory: "Indoor Recreation",
    permissions: {
      residential: 'not_allowed',
      b1: 'special_use',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Arcade / Game Room",
    category: "Commercial - Recreation",
    zoningCategory: "Indoor Recreation",
    permissions: {
      residential: 'not_allowed',
      b1: 'special_use',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'special_use',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'not_allowed',
      pmd: 'special_use',
    }
  },
  {
    name: "Golf Course / Driving Range",
    category: "Commercial - Recreation",
    zoningCategory: "Outdoor Recreation",
    permissions: {
      residential: 'special_use',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'special_use',
      c1: 'not_allowed',
      c2: 'special_use',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'permitted',
      pmd: 'special_use',
    }
  },

  // C.20 Repair Services
  {
    name: "Repair Services (Consumer Goods)",
    category: "Commercial - Services",
    zoningCategory: "Repair Service, Consumer Goods",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },

  // C.21 Retail Sales
  {
    name: "Retail Store (General)",
    category: "Commercial - Retail",
    zoningCategory: "Retail Sales, General",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Pharmacy / Drug Store",
    category: "Commercial - Retail",
    zoningCategory: "Retail Sales, General",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Furniture Store",
    category: "Commercial - Retail",
    zoningCategory: "Retail Sales, General",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Electronics Store",
    category: "Commercial - Retail",
    zoningCategory: "Retail Sales, General",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Clothing / Apparel Store",
    category: "Commercial - Retail",
    zoningCategory: "Retail Sales, General",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Hardware Store",
    category: "Commercial - Retail",
    zoningCategory: "Retail Sales, General",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Outdoor Sales (Temporary)",
    category: "Commercial - Retail",
    zoningCategory: "Outdoor Sales, Temporary",
    permissions: {
      residential: 'not_allowed',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Building Materials Sales",
    category: "Commercial - Retail",
    zoningCategory: "Building Materials Sales",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'permitted',
      c1: 'not_allowed',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },

  // C.22 Cannabis Uses
  {
    name: "Cannabis Dispensary",
    category: "Commercial - Cannabis",
    zoningCategory: "Cannabis Dispensing Organization",
    permissions: {
      residential: 'not_allowed',
      b1: 'special_use',
      b2: 'special_use',
      b3: 'special_use',
      c1: 'special_use',
      c2: 'special_use',
      c3: 'special_use',
      dc: 'special_use',
      dx: 'special_use',
      ds: 'special_use',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'special_use',
      pmd: 'special_use',
    }
  },
  {
    name: "Cannabis Craft Grower",
    category: "Commercial - Cannabis",
    zoningCategory: "Cannabis Craft Grower",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'not_allowed',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'special_use',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'special_use',
      pmd: 'special_use',
    }
  },
  {
    name: "Cannabis Infuser",
    category: "Commercial - Cannabis",
    zoningCategory: "Cannabis Infuser Organization",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'not_allowed',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'special_use',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'special_use',
      pmd: 'special_use',
    }
  },
  {
    name: "Cannabis Transporter",
    category: "Commercial - Cannabis",
    zoningCategory: "Cannabis Transporter",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'not_allowed',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Cannabis Cultivation Center",
    category: "Commercial - Cannabis",
    zoningCategory: "Cannabis Cultivation Center",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'not_allowed',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'not_allowed',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'special_use',
      pmd: 'special_use',
    }
  },

  // ============================================
  // D. VEHICULAR USES
  // ============================================
  {
    name: "Gas Station",
    category: "Vehicular",
    zoningCategory: "Gas Station",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'special_use',
      b3: 'special_use',
      c1: 'not_allowed',
      c2: 'special_use',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'special_use',
    }
  },
  {
    name: "Auto Repair (Minor)",
    category: "Vehicular",
    zoningCategory: "Vehicle Repair, Minor",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'permitted',
      c1: 'not_allowed',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Auto Repair (Major) / Body Shop",
    category: "Vehicular",
    zoningCategory: "Vehicle Repair, Major",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'special_use',
      c1: 'not_allowed',
      c2: 'special_use',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Car Wash",
    category: "Vehicular",
    zoningCategory: "Car Wash",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'special_use',
      b3: 'permitted',
      c1: 'not_allowed',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Vehicle Sales / Rental (Indoor)",
    category: "Vehicular",
    zoningCategory: "Vehicle Sales/Rental",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'not_allowed',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Vehicle Sales / Rental (Outdoor)",
    category: "Vehicular",
    zoningCategory: "Vehicle Sales/Rental",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'special_use',
      b3: 'permitted',
      c1: 'not_allowed',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Drive-Through Facility",
    category: "Vehicular",
    zoningCategory: "Drive-Through Facility",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'special_use',
      b3: 'permitted',
      c1: 'not_allowed',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Truck Terminal",
    category: "Vehicular",
    zoningCategory: "Truck Terminal",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'not_allowed',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'special_use',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "EV Charging Station",
    category: "Vehicular",
    zoningCategory: "Electric Vehicle Charging Station",
    permissions: {
      residential: 'permitted',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },

  // ============================================
  // E. INDUSTRIAL USES
  // ============================================
  {
    name: "Manufacturing (Light)",
    category: "Industrial",
    zoningCategory: "Manufacturing, Processing, Assembling",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'not_allowed',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Manufacturing (Heavy)",
    category: "Industrial",
    zoningCategory: "Manufacturing, Processing, Assembling",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'not_allowed',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'not_allowed',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'not_allowed',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Brewery / Distillery / Winery (Production)",
    category: "Industrial",
    zoningCategory: "Manufacturing, Processing, Assembling",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'special_use',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Food Production / Commercial Kitchen",
    category: "Industrial",
    zoningCategory: "Manufacturing, Processing, Assembling",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'special_use',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Warehouse / Distribution",
    category: "Industrial",
    zoningCategory: "Warehousing, Storage, Distribution",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'special_use',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Self-Storage Facility",
    category: "Industrial",
    zoningCategory: "Mini-Warehouse",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'special_use',
      c1: 'not_allowed',
      c2: 'special_use',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Recycling Facility (Class I)",
    category: "Industrial",
    zoningCategory: "Recycling Facility, Class I",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'not_allowed',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Recycling Facility (Class II-III)",
    category: "Industrial",
    zoningCategory: "Recycling Facility, Class II-III",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'not_allowed',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'not_allowed',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'special_use',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'special_use',
    }
  },
  {
    name: "Data Center",
    category: "Industrial",
    zoningCategory: "Data Center",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'permitted',
      c1: 'not_allowed',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Contractor / Trade Facility",
    category: "Industrial",
    zoningCategory: "Contractor/Trade Facility",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'permitted',
      c1: 'not_allowed',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Outdoor Storage (Accessory)",
    category: "Industrial",
    zoningCategory: "Outdoor Storage, Accessory",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'permitted',
      c1: 'not_allowed',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Scrap Metal / Salvage Yard",
    category: "Industrial",
    zoningCategory: "Scrap Metal Processing",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'not_allowed',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'not_allowed',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'not_allowed',
      m2: 'special_use',
      m3: 'permitted',
      pmd: 'special_use',
    }
  },

  // ============================================
  // F. OTHER / SPECIAL USES
  // ============================================
  {
    name: "Adult Entertainment",
    category: "Other",
    zoningCategory: "Adult Use",
    permissions: {
      residential: 'not_allowed',
      b1: 'not_allowed',
      b2: 'not_allowed',
      b3: 'not_allowed',
      c1: 'not_allowed',
      c2: 'not_allowed',
      c3: 'not_allowed',
      dc: 'not_allowed',
      dx: 'not_allowed',
      ds: 'not_allowed',
      m1: 'special_use',
      m2: 'special_use',
      m3: 'special_use',
      pmd: 'not_allowed',
    }
  },
  {
    name: "Urban Farm (Outdoor)",
    category: "Other",
    zoningCategory: "Urban Farm",
    permissions: {
      residential: 'permitted',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Community Garden",
    category: "Other",
    zoningCategory: "Community Garden",
    permissions: {
      residential: 'permitted',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
  {
    name: "Rooftop Garden / Greenhouse",
    category: "Other",
    zoningCategory: "Rooftop Garden",
    permissions: {
      residential: 'permitted',
      b1: 'permitted',
      b2: 'permitted',
      b3: 'permitted',
      c1: 'permitted',
      c2: 'permitted',
      c3: 'permitted',
      dc: 'permitted',
      dx: 'permitted',
      ds: 'permitted',
      m1: 'permitted',
      m2: 'permitted',
      m3: 'permitted',
      pmd: 'permitted',
    }
  },
];

export function getBusinessUseCategories(): string[] {
  const categories = new Set(BUSINESS_USES.map(u => u.category));
  return Array.from(categories).sort();
}

export function getBusinessUsesByCategory(category: string): BusinessUse[] {
  return BUSINESS_USES.filter(u => u.category === category);
}

export function getBusinessUseByName(name: string): BusinessUse | undefined {
  return BUSINESS_USES.find(u => u.name === name);
}

export function checkZoningCompatibility(
  businessUseName: string,
  zoningCode: string
): { permission: ZoningPermission; message: string } {
  const use = getBusinessUseByName(businessUseName);
  if (!use) {
    return { permission: 'not_allowed', message: 'Unknown business use type' };
  }

  const normalizedCode = zoningCode.toUpperCase().trim();
  
  let permission: ZoningPermission = 'not_allowed';
  
  if (normalizedCode.startsWith('RS') || normalizedCode.startsWith('RT') || normalizedCode.startsWith('RM')) {
    permission = use.permissions.residential;
  } else if (normalizedCode.startsWith('B1')) {
    permission = use.permissions.b1;
  } else if (normalizedCode.startsWith('B2')) {
    permission = use.permissions.b2;
  } else if (normalizedCode.startsWith('B3')) {
    permission = use.permissions.b3;
  } else if (normalizedCode.startsWith('C1')) {
    permission = use.permissions.c1;
  } else if (normalizedCode.startsWith('C2')) {
    permission = use.permissions.c2;
  } else if (normalizedCode.startsWith('C3')) {
    permission = use.permissions.c3;
  } else if (normalizedCode.startsWith('DC')) {
    permission = use.permissions.dc;
  } else if (normalizedCode.startsWith('DX')) {
    permission = use.permissions.dx;
  } else if (normalizedCode.startsWith('DS')) {
    permission = use.permissions.ds;
  } else if (normalizedCode.startsWith('M1')) {
    permission = use.permissions.m1;
  } else if (normalizedCode.startsWith('M2')) {
    permission = use.permissions.m2;
  } else if (normalizedCode.startsWith('M3')) {
    permission = use.permissions.m3;
  } else if (normalizedCode.startsWith('PMD')) {
    permission = use.permissions.pmd;
  } else if (normalizedCode.startsWith('PD')) {
    return { permission: 'special_use', message: 'Planned Development - check specific PD ordinance for allowed uses' };
  } else if (normalizedCode.startsWith('POS')) {
    return { permission: 'not_allowed', message: 'Parks and Open Space district - limited uses allowed' };
  }

  const messages: Record<ZoningPermission, string> = {
    permitted: `${use.name} is permitted as-of-right in ${zoningCode} zoning.`,
    special_use: `${use.name} requires Special Use approval in ${zoningCode} zoning.`,
    not_allowed: `${use.name} is not allowed in ${zoningCode} zoning.`,
  };

  return { permission, message: messages[permission] };
}
