import type { ZoningInfo } from './schema';

export const CHICAGO_ZONING_DATA: Record<string, ZoningInfo> = {
  'RS-1': {
    code: 'RS-1',
    name: 'Residential Single-Unit (Detached House)',
    category: 'residential',
    description: 'Single-family detached houses on large lots',
    allowedUses: ['Single-family detached homes', 'Parks and open space', 'Religious assembly', 'Daycare (with limits)'],
    maxFAR: 0.5,
    maxHeight: '30 feet (2 stories)',
    parkingMin: '1 space / unit',
    minLotAreaPerUnit: 6250,
    residentialAllowed: true,
    commercialAllowed: false,
    industrialAllowed: false,
  },
  'RS-2': {
    code: 'RS-2',
    name: 'Residential Single-Unit (Detached House)',
    category: 'residential',
    description: 'Single-family detached houses on medium lots',
    allowedUses: ['Single-family detached homes', 'Two-flats (limited)', 'Parks', 'Religious assembly', 'Daycare'],
    maxFAR: 0.65,
    maxHeight: '30 feet (2 stories)',
    parkingMin: '1 space / unit',
    minLotAreaPerUnit: 3000,
    residentialAllowed: true,
    commercialAllowed: false,
    industrialAllowed: false,
  },
  'RS-3': {
    code: 'RS-3',
    name: 'Residential Single-Unit (Detached House)',
    category: 'residential',
    description: 'Single-family detached houses on standard city lots',
    allowedUses: ['Single-family detached homes', 'Two-flats (limited)', 'Parks', 'Religious assembly', 'Daycare', 'Public safety facilities'],
    maxFAR: 0.9,
    maxHeight: '30 feet (2 stories)',
    parkingMin: '1 space / unit',
    minLotAreaPerUnit: 2500,
    residentialAllowed: true,
    commercialAllowed: false,
    industrialAllowed: false,
  },
  'RT-3.5': {
    code: 'RT-3.5',
    name: 'Residential Two-Flat, Townhouse and Multi-Unit',
    category: 'residential',
    description: 'Low-density residential with two-flats and townhouses',
    allowedUses: ['Single-family homes', 'Two-flats', 'Townhouses', 'Small multi-unit buildings', 'Parks', 'Religious assembly'],
    maxFAR: 1.05,
    maxHeight: '35 feet (3 stories)',
    parkingMin: '1 space / unit',
    minLotAreaPerUnit: 1500,
    residentialAllowed: true,
    commercialAllowed: false,
    industrialAllowed: false,
  },
  'RT-4': {
    code: 'RT-4',
    name: 'Residential Two-Flat, Townhouse and Multi-Unit',
    category: 'residential',
    description: 'Low-density mixed housing types compatible with single-family areas',
    allowedUses: ['Single-family homes', 'Two-flats', 'Townhouses', 'Multi-unit apartments (up to 3 units per standard lot)', 'Parks', 'Religious assembly', 'Daycare'],
    maxFAR: 1.2,
    maxHeight: '38 feet (3 stories)',
    parkingMin: '1 space / unit',
    minLotAreaPerUnit: 1000,
    residentialAllowed: true,
    commercialAllowed: false,
    industrialAllowed: false,
  },
  'RM-4.5': {
    code: 'RM-4.5',
    name: 'Residential Multi-Unit',
    category: 'residential',
    description: 'Medium-density multi-unit residential buildings',
    allowedUses: ['Multi-unit residential buildings', 'Townhouses', 'Two-flats', 'Parks', 'Religious assembly', 'Daycare', 'Elderly housing'],
    maxFAR: 1.7,
    maxHeight: '45 feet (4 stories)',
    parkingMin: '1 space / unit',
    minLotAreaPerUnit: 400,
    residentialAllowed: true,
    commercialAllowed: false,
    industrialAllowed: false,
  },
  'RM-5': {
    code: 'RM-5',
    name: 'Residential Multi-Unit',
    category: 'residential',
    description: 'Medium-high density multi-unit residential',
    allowedUses: ['Multi-unit residential buildings', 'Apartment buildings', 'Senior housing', 'Parks', 'Religious assembly'],
    maxFAR: 2.0,
    maxHeight: '55 feet (5 stories)',
    parkingMin: '1 space / unit',
    minLotAreaPerUnit: 200,
    residentialAllowed: true,
    commercialAllowed: false,
    industrialAllowed: false,
  },
  'RM-6': {
    code: 'RM-6',
    name: 'Residential Multi-Unit',
    category: 'residential',
    description: 'High-density multi-unit residential',
    allowedUses: ['High-rise apartments', 'Multi-unit buildings', 'Senior housing', 'Religious assembly'],
    maxFAR: 4.4,
    maxHeight: 'No limit',
    parkingMin: '1 space / unit',
    minLotAreaPerUnit: 100,
    residentialAllowed: true,
    commercialAllowed: false,
    industrialAllowed: false,
  },
  'B1-1': {
    code: 'B1-1',
    name: 'Neighborhood Shopping',
    category: 'business',
    description: 'Small-scale retail and services for neighborhoods',
    allowedUses: ['Retail stores', 'Restaurants', 'Personal services', 'Banks', 'Offices', 'Residential above ground floor'],
    maxFAR: 1.2,
    maxHeight: '38 feet (3 stories)',
    parkingMin: '1 space / unit (residential)',
    minLotAreaPerUnit: 1000,
    residentialAllowed: true,
    commercialAllowed: true,
    industrialAllowed: false,
  },
  'B1-2': {
    code: 'B1-2',
    name: 'Neighborhood Shopping',
    category: 'business',
    description: 'Medium-scale retail and services',
    allowedUses: ['Retail stores', 'Restaurants', 'Personal services', 'Banks', 'Offices', 'Residential above ground floor'],
    maxFAR: 2.2,
    maxHeight: '50 feet (4 stories)',
    parkingMin: '1 space / unit (residential)',
    minLotAreaPerUnit: 1000,
    residentialAllowed: true,
    commercialAllowed: true,
    industrialAllowed: false,
  },
  'B2-2': {
    code: 'B2-2',
    name: 'Neighborhood Mixed-Use',
    category: 'business',
    description: 'Mixed commercial and residential along main streets',
    allowedUses: ['Retail', 'Restaurants', 'Bars', 'Entertainment', 'Offices', 'Residential above ground floor', 'Hotels'],
    maxFAR: 2.2,
    maxHeight: '50 feet (4 stories)',
    parkingMin: '1 space / unit (residential)',
    minLotAreaPerUnit: 1000,
    residentialAllowed: true,
    commercialAllowed: true,
    industrialAllowed: false,
  },
  'B3-1': {
    code: 'B3-1',
    name: 'Community Shopping',
    category: 'business',
    description: 'Shopping centers and large stores along major streets',
    allowedUses: ['Shopping centers', 'Large retail stores', 'Liquor stores', 'Auto repair (indoor)', 'Warehouses', 'Offices', 'Residential above ground floor'],
    maxFAR: 1.2,
    maxHeight: '38 feet (3 stories)',
    parkingMin: '1 space / unit (residential)',
    minLotAreaPerUnit: 1000,
    residentialAllowed: true,
    commercialAllowed: true,
    industrialAllowed: false,
  },
  'B3-2': {
    code: 'B3-2',
    name: 'Community Shopping',
    category: 'business',
    description: 'Medium-density shopping and commercial',
    allowedUses: ['Shopping centers', 'Large retail', 'Auto sales (indoor)', 'Warehouses', 'Light manufacturing', 'Residential above ground floor'],
    maxFAR: 2.2,
    maxHeight: '50 feet (4 stories)',
    parkingMin: '1 space / unit (residential)',
    minLotAreaPerUnit: 1000,
    residentialAllowed: true,
    commercialAllowed: true,
    industrialAllowed: false,
  },
  'B3-3': {
    code: 'B3-3',
    name: 'Community Shopping',
    category: 'business',
    description: 'Higher-density community commercial',
    allowedUses: ['Shopping centers', 'Large retail', 'Offices', 'Light manufacturing', 'Residential'],
    maxFAR: 3.0,
    maxHeight: '65 feet (5 stories)',
    parkingMin: '1 space / unit (residential)',
    minLotAreaPerUnit: 1000,
    residentialAllowed: true,
    commercialAllowed: true,
    industrialAllowed: false,
  },
  'C1-1': {
    code: 'C1-1',
    name: 'Neighborhood Commercial',
    category: 'commercial',
    description: 'Local commercial services',
    allowedUses: ['Retail', 'Restaurants', 'Personal services', 'Offices', 'Residential above ground floor'],
    maxFAR: 1.2,
    maxHeight: '38 feet',
    parkingMin: '1 space / unit (residential)',
    minLotAreaPerUnit: 1000,
    residentialAllowed: true,
    commercialAllowed: true,
    industrialAllowed: false,
  },
  'C1-2': {
    code: 'C1-2',
    name: 'Neighborhood Commercial',
    category: 'commercial',
    description: 'Medium-density neighborhood commercial',
    allowedUses: ['Retail', 'Restaurants', 'Personal services', 'Offices', 'Residential above ground floor'],
    maxFAR: 2.2,
    maxHeight: '50 feet',
    parkingMin: '1 space / unit (residential)',
    minLotAreaPerUnit: 1000,
    residentialAllowed: true,
    commercialAllowed: true,
    industrialAllowed: false,
  },
  'C2-2': {
    code: 'C2-2',
    name: 'Motor Vehicle-Related Commercial',
    category: 'commercial',
    description: 'Auto-oriented commercial with drive-throughs',
    allowedUses: ['Auto dealers', 'Gas stations', 'Drive-through restaurants', 'Auto repair', 'Retail', 'Offices'],
    maxFAR: 2.2,
    maxHeight: '50 feet',
    parkingMin: '1 space / unit (residential)',
    minLotAreaPerUnit: 1000,
    residentialAllowed: true,
    commercialAllowed: true,
    industrialAllowed: false,
  },
  'M1-1': {
    code: 'M1-1',
    name: 'Limited Manufacturing/Business Park',
    category: 'manufacturing',
    description: 'Light industrial and business park uses',
    allowedUses: ['Light manufacturing', 'Warehouses', 'Offices', 'Research facilities', 'Wholesale', 'Limited retail'],
    maxFAR: 1.2,
    maxHeight: '38 feet',
    parkingMin: '1 per 1,000 sq ft',
    minLotAreaPerUnit: null,
    residentialAllowed: false,
    commercialAllowed: true,
    industrialAllowed: true,
  },
  'M1-2': {
    code: 'M1-2',
    name: 'Limited Manufacturing/Business Park',
    category: 'manufacturing',
    description: 'Medium-density light industrial',
    allowedUses: ['Light manufacturing', 'Warehouses', 'Offices', 'Research facilities', 'Wholesale'],
    maxFAR: 2.2,
    maxHeight: '50 feet',
    parkingMin: '1 per 1,000 sq ft',
    minLotAreaPerUnit: null,
    residentialAllowed: false,
    commercialAllowed: true,
    industrialAllowed: true,
  },
  'M2-2': {
    code: 'M2-2',
    name: 'General Manufacturing',
    category: 'manufacturing',
    description: 'General industrial and manufacturing',
    allowedUses: ['Manufacturing', 'Heavy industrial', 'Warehouses', 'Freight terminals', 'Recycling facilities'],
    maxFAR: 2.2,
    maxHeight: '50 feet',
    parkingMin: '1 per 2,000 sq ft',
    minLotAreaPerUnit: null,
    residentialAllowed: false,
    commercialAllowed: false,
    industrialAllowed: true,
  },
  'M3-3': {
    code: 'M3-3',
    name: 'Heavy Manufacturing',
    category: 'manufacturing',
    description: 'Heavy industrial uses',
    allowedUses: ['Heavy manufacturing', 'Industrial processing', 'Waste facilities', 'Freight operations'],
    maxFAR: 3.0,
    maxHeight: 'No limit',
    parkingMin: 'Varies by use',
    minLotAreaPerUnit: null,
    residentialAllowed: false,
    commercialAllowed: false,
    industrialAllowed: true,
  },
  'PMD-1': {
    code: 'PMD-1',
    name: 'Planned Manufacturing District',
    category: 'special',
    description: 'Protected industrial corridor - Goose Island',
    allowedUses: ['Manufacturing', 'Warehouses', 'Industrial support services', 'Limited commercial'],
    maxFAR: null,
    maxHeight: null,
    parkingMin: '1 per 1,000 sq ft',
    minLotAreaPerUnit: null,
    residentialAllowed: false,
    commercialAllowed: false,
    industrialAllowed: true,
  },
  'PMD-2': {
    code: 'PMD-2',
    name: 'Planned Manufacturing District',
    category: 'special',
    description: 'Protected industrial corridor - Elston',
    allowedUses: ['Manufacturing', 'Warehouses', 'Industrial support services'],
    maxFAR: null,
    maxHeight: null,
    parkingMin: '1 per 1,000 sq ft',
    minLotAreaPerUnit: null,
    residentialAllowed: false,
    commercialAllowed: false,
    industrialAllowed: true,
  },
  'PMD-3': {
    code: 'PMD-3',
    name: 'Planned Manufacturing District',
    category: 'special',
    description: 'Protected industrial corridor - Kinzie',
    allowedUses: ['Manufacturing', 'Warehouses', 'Industrial support services', 'Daycare (permitted)'],
    maxFAR: null,
    maxHeight: null,
    parkingMin: '1 per 1,000 sq ft',
    minLotAreaPerUnit: null,
    residentialAllowed: false,
    commercialAllowed: false,
    industrialAllowed: true,
  },
  'PMD-4': {
    code: 'PMD-4',
    name: 'Planned Manufacturing District',
    category: 'special',
    description: 'Protected industrial corridor - Kinzie Industrial Corridor',
    allowedUses: ['Manufacturing', 'Warehouses', 'Industrial support services', 'Daycare (permitted)', 'Food production'],
    maxFAR: null,
    maxHeight: null,
    parkingMin: '1 per 1,000 sq ft',
    minLotAreaPerUnit: null,
    residentialAllowed: false,
    commercialAllowed: false,
    industrialAllowed: true,
  },
  'DX-3': {
    code: 'DX-3',
    name: 'Downtown Mixed-Use',
    category: 'downtown',
    description: 'Downtown core mixed-use development',
    allowedUses: ['Office towers', 'Residential high-rises', 'Retail', 'Hotels', 'Entertainment', 'Cultural facilities'],
    maxFAR: 3.0,
    maxHeight: 'No limit',
    parkingMin: 'None required',
    minLotAreaPerUnit: null,
    residentialAllowed: true,
    commercialAllowed: true,
    industrialAllowed: false,
  },
  'DX-5': {
    code: 'DX-5',
    name: 'Downtown Mixed-Use',
    category: 'downtown',
    description: 'High-density downtown development',
    allowedUses: ['Office towers', 'Residential high-rises', 'Retail', 'Hotels', 'Entertainment'],
    maxFAR: 5.0,
    maxHeight: 'No limit',
    parkingMin: 'None required',
    minLotAreaPerUnit: null,
    residentialAllowed: true,
    commercialAllowed: true,
    industrialAllowed: false,
  },
  'DX-7': {
    code: 'DX-7',
    name: 'Downtown Mixed-Use',
    category: 'downtown',
    description: 'Maximum density downtown development',
    allowedUses: ['Skyscrapers', 'Office towers', 'Residential high-rises', 'Major retail', 'Hotels'],
    maxFAR: 7.0,
    maxHeight: 'No limit',
    parkingMin: 'None required',
    minLotAreaPerUnit: null,
    residentialAllowed: true,
    commercialAllowed: true,
    industrialAllowed: false,
  },
  'DC-12': {
    code: 'DC-12',
    name: 'Downtown Core',
    category: 'downtown',
    description: 'Highest density downtown core',
    allowedUses: ['Major office towers', 'Landmark buildings', 'Major retail', 'Hotels', 'Cultural institutions'],
    maxFAR: 12.0,
    maxHeight: 'No limit',
    parkingMin: 'None required',
    minLotAreaPerUnit: null,
    residentialAllowed: true,
    commercialAllowed: true,
    industrialAllowed: false,
  },
  'POS-1': {
    code: 'POS-1',
    name: 'Parks and Open Space',
    category: 'special',
    description: 'Public parks and recreational areas',
    allowedUses: ['Parks', 'Playgrounds', 'Recreation facilities', 'Nature preserves'],
    maxFAR: null,
    maxHeight: null,
    parkingMin: null,
    minLotAreaPerUnit: null,
    residentialAllowed: false,
    commercialAllowed: false,
    industrialAllowed: false,
  },
  'PD': {
    code: 'PD',
    name: 'Planned Development',
    category: 'special',
    description: 'Special planned development - check specific PD ordinance',
    allowedUses: ['Varies by specific PD ordinance - consult Chicago DPD'],
    maxFAR: null,
    maxHeight: null,
    parkingMin: 'Set by ordinance',
    minLotAreaPerUnit: null,
    residentialAllowed: true,
    commercialAllowed: true,
    industrialAllowed: true,
  },
};

export function getZoningInfo(code: string): ZoningInfo | null {
  if (!code) return null;
  
  const normalizedCode = code.toUpperCase().trim();
  
  if (CHICAGO_ZONING_DATA[normalizedCode]) {
    return CHICAGO_ZONING_DATA[normalizedCode];
  }
  
  const baseCode = normalizedCode.replace(/-\d+$/, '');
  const matchingCodes = Object.keys(CHICAGO_ZONING_DATA).filter(k => k.startsWith(baseCode));
  
  if (matchingCodes.length > 0) {
    const template = CHICAGO_ZONING_DATA[matchingCodes[0]];
    return {
      ...template,
      code: normalizedCode,
      name: template.name,
    };
  }
  
  return null;
}
